title: Said Hassan
description: >-
  Postdoctoral Prize Research Fellow, Nuffield College, University of Oxford
# Use the built-in Minimal theme on GitHub Pages
theme: jekyll-theme-minimal

# Optional settings
logo: /assets/img/profile.jpg   # put your headshot at assets/img/profile.jpg
header img {
  border-radius: 20%;   /* adjust % for more/less oval */
}
show_downloads: false
google_analytics:
# If you're using a custom domain, set it in Pages settings (it will create a CNAME file automatically).
# For a user site at https://<username>.github.io, leave baseurl empty and set url accordingly:
url: "https://s-aj-hassan.github.io"
baseurl: ""
